// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-LmICDptsStiNAKz-_ELKBRkj5YUvgZY',
    appId: '1:361646362895:web:ec565998c7101599d66e7a',
    messagingSenderId: '361646362895',
    projectId: 'prolingo-5cc1d',
    authDomain: 'prolingo-5cc1d.firebaseapp.com',
    storageBucket: 'prolingo-5cc1d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV2dG6kzAp1zHWaurpXhsuAeBWfzlzWk0',
    appId: '1:361646362895:android:f61e46943db6a1afd66e7a',
    messagingSenderId: '361646362895',
    projectId: 'prolingo-5cc1d',
    storageBucket: 'prolingo-5cc1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbfNor4Ua30UXE5_o99G3A_rzdvNIryOc',
    appId: '1:361646362895:ios:200c4c75d770115ed66e7a',
    messagingSenderId: '361646362895',
    projectId: 'prolingo-5cc1d',
    storageBucket: 'prolingo-5cc1d.firebasestorage.app',
    iosBundleId: 'com.example.prolingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbfNor4Ua30UXE5_o99G3A_rzdvNIryOc',
    appId: '1:361646362895:ios:200c4c75d770115ed66e7a',
    messagingSenderId: '361646362895',
    projectId: 'prolingo-5cc1d',
    storageBucket: 'prolingo-5cc1d.firebasestorage.app',
    iosBundleId: 'com.example.prolingo',
  );
}
